//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whitehole.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Whitehole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   # .pa files (collision behaviors)
        ///camera_id
        ///Sound_code
        ///Floor_code
        ///Wall_code
        ///Camera_through
        ///
        ///# zonelist.bcsv
        ///ZoneName
        ///
        ///# scenariodata.bcsv
        ///ScenarioNo
        ///ScenarioName
        ///PowerStarId
        ///AppearPowerStarObj
        ///Comet
        ///LuigiModeTimer
        ///IsHidden
        ///# TODO: D6C80400
        ///
        ///# changescenelistinfo
        ///SceneNo
        ///MarioNo
        ///
        ///# commonpathpointinfo
        ///point_arg0
        ///point_arg1
        ///point_arg2
        ///point_arg3
        ///point_arg4
        ///point_arg5
        ///point_arg6
        ///point_arg7
        ///
        ///# names below extracted from Anarchy in the Galaxy
        ///# credit goes to Phantom Wings (or  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KnownFieldNames {
            get {
                return ResourceManager.GetString("KnownFieldNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   # AstroGalaxy
        ///$DomeTable = { 1:Observatory; 2:Well; 3:Kitchen; 4:BedRoom; 5:Machine; 6:Tower }
        ///AstroDomeEntrance: FileName=String(AstroDomeEntrance{$DomeTable[Obj_arg0]})
        ///AstroStarPlate: FileName=String(AstroStarPlate{$DomeTable[Obj_arg0]})
        ///
        ///SuperSpinDriverGreen: FileName=String(SuperSpinDriverEmpty)
        ///
        ///# FactoryGalaxy
        ///OnimasuPivot: FileName=String(Onimasu)
        ///
        ///# HeavenlyBeachGalaxy
        ///#OceanBowl: FileName=String(HeavenlyBeachPlanetWater); Scale=Vector3(0.0138888889,0.0138888889,0.0138888889)
        ///#OceanBowl [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ObjectRenderInfo {
            get {
                return ResourceManager.GetString("ObjectRenderInfo", resourceCulture);
            }
        }
    }
}
